# Generated by Django 2.2.7 on 2019-12-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('braintree_subscription_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('subscription_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('shipping_details', models.TextField(blank=True, default=None, null=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('number_of_months', models.IntegerField(blank=True, default=None, null=True)),
                ('reason_for_canceling', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
