# Generated by Django 2.2.7 on 2019-12-18 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_subscription_archive_next_billing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_archive',
            old_name='next_billing_date',
            new_name='billing_day_of_month',
        ),
    ]
