# Generated by Django 2.2.7 on 2020-01-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20191218_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_archive',
            name='next_billing_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
