# Generated by Django 2.2.7 on 2019-12-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='expiration',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
