# Generated by Django 2.2.7 on 2019-12-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_paymentdetails_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='activte_status',
            new_name='active_status',
        ),
    ]
