# Generated by Django 2.2.7 on 2019-12-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20191211_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='braintree_scubscription_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
