# Generated by Django 2.2.7 on 2019-12-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_subscription_braintree_scubscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='braintree_scubscription_id',
            new_name='braintree_subscription_id',
        ),
    ]
