# Generated by Django 2.2.7 on 2019-12-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20191212_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='address_details',
            new_name='shipping_details',
        ),
    ]
