# Generated by Django 2.2.7 on 2019-12-13 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20191213_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='gift_address',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_address', to='Accounts.ShippingDetails'),
        ),
    ]
