# Generated by Django 2.2.7 on 2019-12-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20191216_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reason_for_canceling',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
