# Generated by Django 2.2.7 on 2019-12-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_auto_20191216_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='shipping_details',
        ),
    ]
