# Generated by Django 2.2.7 on 2019-12-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_remove_subscription_shipping_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_nonce',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
