# Generated by Django 2.2.7 on 2019-12-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_paymentdetails_payment_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_bill_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
