# Generated by Django 2.2.7 on 2019-12-18 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_subscription_next_bill_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='next_bill_date',
            new_name='billing_day_of_month',
        ),
    ]
