# Generated by Django 2.2.7 on 2020-01-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_auto_20200107_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_billing_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
