# Generated by Django 2.2.7 on 2020-01-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_subscription_next_billing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='customer_id',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
