# Generated by Django 2.2.7 on 2020-01-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0023_paymentdetails_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='customer',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.Customer'),
        ),
    ]
