# Generated by Django 2.2.7 on 2020-01-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0025_auto_20200107_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
