# Generated by Django 2.2.7 on 2020-01-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0027_discounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discounts',
            new_name='Discount',
        ),
    ]
