# Generated by Django 2.2.9 on 2020-01-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0028_auto_20200109_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='this_month_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
